### ISSUE TITLE
[bug]: fix website on 2xl

### ISSUE THREAD

**Issue by avalynndev** [devxoshakya/anveshna#10]
You website navbar works perfectly fine on devices which have screen size xl.. my device has larger screen.. the search bar disappears when i increase my screen length

**Comment by devxoshakya** [comment]
can you share your screen dimensions also a screenshot for reference.
It may occur as the website may not be configured for your screen size.

**Comment by avalynndev** [comment]
image of website on 125% zoom.. (works fine)
![image](https://github.com/devxoshakya/anveshna/assets/100826194/32bcb3f5-6403-49ea-8fd0-43c23dd1ab8a)
image of website on 100% zoom.. search bar died and navbar is pushed
![image](https://github.com/devxoshakya/anveshna/assets/100826194/59a830cf-eadf-4a2d-a02e-c9857044271f)
