### ISSUE TITLE
can u

### ISSUE THREAD

**Issue by bouhamla7** [devxoshakya/anveshna#8]
can u add zoro server with multi sub

**Comment by devxoshakya** [comment]
We can add multi sub, but currently the api is restricted that kind of usage. Furthermore, if you want to just watch anime in English  dub you can just add -dub after the anime name in the url.
`https://anveshna.xyz/{animeID}/{animeTitle}-dub/{episodeNumber}`
Currently the dub version is in development, so there may be some bugs.
