### ISSUE TITLE
[Bug] Watch page anime info not showing.

### ISSUE THREAD

**Issue by skgupta507** [devxoshakya/anveshna#9]
Hey @devxoshakya the Anime info is nit showing on the anime page.
can u pls look into it.
i have added the screenshot for ur reference.
![image](https://github.com/devxoshakya/anveshna/assets/131786207/3da7b013-f771-45cc-a68b-652ebe35cec7)

**Comment by devxoshakya** [comment]
I have been informed about this bug, it is due to the unpredictable api output for airing anime i.e. the anime info is visible for aired animes and I have been working on to fix this issue.

**Comment by devxoshakya** [comment]
I will look it up !!

**Comment by devxoshakya** [comment]
the issue has been fixed in the latest deployment.
